server:
  port: 8081

spring:
  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spoc?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      # 连接池名
      pool-name: DataHikariCP
      # 最小空闲连接数
      minimum-idle: 5
      # 空闲连接存活最大时间，默认十分钟
      idle-timeout: 180000
      # 最大连接数，默认10
      maximum-pool-size: 10
      # 从连接池返回的连接的自动提交
      auto-commit: true
      # 连接最大存活时间，0 表示永久存活，默认30分钟
      max-lifetime: 1800000
      # 连接超时时间，默认30000 30s
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  # redis配置
  redis:
    # 服务器地址
    host: localhost
    # 端口
    port: 6379
    # 数据库
    database: 0
    # 超时时间：2000毫秒
    timeout: 2000ms
    # 密码
    password:
    # 配置lettuce连接池
    lettuce:
      pool:
        # 最大连接数，默认8
        max-active: 5
        # 最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
        # 最大空闲连接，默认8
        max-idle: 10
        # 最小空闲连接，默认0
        min-idle: 5





# Mybatis SQl 打印方法接口所在的包，不是Mapper.xml所在的包
logging:
  level:
    com.xxx.server.mapper: debug

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # jwt加解密使用的密钥
  secret: wb-secret
  # jwt的超限时间（60*60*24）
  expiration: 604800
  #jwt 负载中拿到开头
  tokenHead: Bearer
